version: '2.0'
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh-user:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpPd1Z4sPqRxMuEvpH2wTalwqHdim3qWs6Lmk43udS3Z8OVaNVCpio47q/Sg0fHWl57PVQ+eC0tNYE6PyhgQjiH9VtMbxPud16Dt++jn2NYRNsW4hB3Ad8IVqo6okeECN9cg+xOlj2dGDvjRpXwtDGFMhwHbuXavGt8KP793GbWq9JEJcxbdMle0KL1vZ1C4stllAFok3nr8pJcYBlYld39WeQm/MmNJlvYk408YOS3gXLNnv0GmaboWiYxlMoqSDX9uT+g+n86tGj6jIpLmW4OFDRhVdgBFmfnGxbfXHaFv5nD7j7C/4meV8JFdIAA/OcbUkIhfpBnxHlAdB/uHvK0CaP3+HzDHh0jk672l8RJrM/SzuHlt8keP1vxgjjgjRt9nrQZ0Y+4Oh85CBUS6LJOkVw58qTGzkKP51JX3Ck2bfJjqml+bZJSLJO/DsY1H8/OX/O9tgXww3ARESfx3KXh3+6pu1TJjLe2AccAYJra2eKHiIfGY2yAiy/Ch3wF8MicozJdHnHQ3QMkPi0C14wrgf/fBWR9oAlbG+C1PmPZCEYvYyyClk5afNG+mj474tjMeOxyFW+VT6B8qUm2C4IYaU4dOPWn/rmaHUA1phUllpOJ6x5YfT20gnljMD5C9jSUiog2Otk30NqRcav++ONQuyY44Dc2pVEPRS+PIe6hQ== yuenricky@rickys-mbp
      - username=swantouser
    expose:
      - port: 22
      - port: 30002
      - port: 30003
      - port: 30004
      - port: 30005
      - port: 30006
      - port: 30007
deployment:
  vm:
    lagrange:
      count: 1
