version: '2.0'
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh-user:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrGCKZaWZsVi2afk2W5mukZWyfBTI5Q7xOCYNlo70k7nk23adFR7rr7USpG7ufqqm0z4y/pVlWFWp4o6mcGPlQXf3fPGxaTCZLvr56qeJYUUvTijopBWE4PruEFI3Evka3v0NhGLTJiZL58GuAVYKBeGUbDa0bk6Uh1aLDOzyv4vo0bfy+uFjBtcgbCuNxxVKq6pqEX5VRY6p6Ekr/SSOepRG0j5QBi2D4vJtSJgaemD2Ww/JYOwA9LRhSC1AAv9MZi1ACmxfwaohBTdVcbfhPFIdKsc3OWNmeULPtrNuc7zjyidHteUDnuU3Iqa3KCyIVYboOEIkOrZns/N4QcwrnkaYqZ5qv+sGi/YieZhAmX3lpVDnk3VPDi1rxwx455AzHzQIQstamnUO45L0ngmUR6pP/gIN79pAj0cL9NPYTWONB+phhVLgmSa1qTxlIfuBv7GoCL+UIC7rDJ76y74lsOB7YpNsYjWhkGhFTiRCLa366v2bH/ieKllctUjcw1L8aImnJDH3xU5WgJdgrohjG3+rDyC0tAAQ/oZfmXS98xIvtxnEzk9IHLWzTljIj98EEd9NVgMr15304bLRoqE394ZglUHXdiR0cnk4PLSuypu8d+wLSLRjuieVAXoP7jTJ8C/PzePWWNlE8e6E//aNIJoQkliK3n24gktPYfMnKGw== yuenricky@rickys-mbp
      - username=swantouser
    expose:
      - port: 22
      - port: 30002
      - port: 30003
      - port: 30004
      - port: 30005
      - port: 30006
      - port: 30007
deployment:
  vm:
    lagrange:
      count: 1
